run:
  timeout: 5m

linters-settings:
  cyclop:
    max-complexity: 30

linters:
  disable-all: true
  enable:
    # Enabled by default.
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # Disabled by default.
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - gosec
    - lll
    - maintidx
    - makezero
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - predeclared
    - promlinter
    - tagliatelle
    - tenv
    - thelper
    - tparallel
    - unconvert
    - wrapcheck
